### ISSUE TITLE
Order items on the desktop, volumes should always be first

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#60]
This is a follow-up from https://github.com/helloSystem/Filer/issues/9.

Would it be possible to adjust the order a bit?

Ideally:
* The "File System" icon (`/`, URL `computer:///root.link`) should always be the first one
* Followed by any other disks (MIME type `inode/mount-point`, URL `computer:///*.mount`) ideally in the order of time when they were mounted (oldest mounts first)
* Everything else, depending on the order set by the user

cc @moochris

**Comment by moochris** [comment]
Yeah, should be possible - I should have a bit more time next weekend to look at this and a few other things

**Comment by moochris** [comment]
I realise I have just fixed the default ordering with that PR (which previously was modified date/time)

I don't really know how you would order the devices first in combination with the sort order chosen by the user.

**Comment by probonopd** [comment]
Thanks for looking into this. Merging your PR, but it's not completely solved yet: Depending on what sort order the user chooses (e.g, by file type, by file name) it still can happen that the volumes are not in front of everything else.

To be clear, the intended behavior is that _only_ the files and folders to be afftected by the sort order the user chooses. The combined model should _not_ be sorted according to the user's choice. Volumes should _always_ be first, and _always_ in the order of when they were mounted.

**Comment by probonopd** [comment]
Thanks @moochris for having resolved this issue. :+1:
